require "ifj21"

function main()
	local a : integer = 4
	local b : nil = nil
	local c : number = 4.0
	local d : number = 4
	local e : string = ""
	local f : string = "abcd"
	local g : string = nil
	local h : number = 1.1e1
	local i : number = 1e1
	local j : number = 1.1
	local k : number = 1e+1
	local l : number = 1e-1
	local m : number = 1.1e+1
	local n : number = 1.1e-1
	local o : number = nil
	write (a,"\n", b,"\n", c,"\n", d,"\n", e,"\n", f,"\n", h,"\n", i,"\n", j,"\n", k,"\n", l,"\n", m,"\n", n,"\n", o, "\n")
end

main()
