require "ifj21"

function main()
    local x:integer
    local y:number
    local z:string
    local n:nil = nil

    if x == n then
        write("yes\n")
    else
        write("no\n")
    end

    if y == n then
        write("yes\n")
    else
        write("no\n")
    end

    if z == n then
        write("yes\n")
    else
        write("no\n")
    end

    if n == n then
        write("yes\n")
    else
        write("no\n")
    end

    if x == nil then
        write("yes\n")
    else
        write("no\n")
    end

    if y == nil then
        write("yes\n")
    else
        write("no\n")
    end

    if z == nil then
        write("yes\n")
    else
        write("no\n")
    end

    if n == nil then
        write("yes\n")
    else
        write("no\n")
    end
end

main()
